#!/bin/bash

PROGNAME=${0##*/}
PROGPATH="$(realpath ${0%/*})"
STARTPATH="$(pwd)"

PROGVERSION="0.0.5"

CONFFILE=$1

set_global()
{
	HEADER=""
	SECTION_HEADER=" - "
	SUBSECTION_HEADER=" --> "

	LOGLEVEL=3
	DRYRUN=false
	IS_SUDOER=false
	ASSUME_YES=false
	NO_INTERNET=false

	DISTRO=""
	SUDOGROUP="wheel"
	DOTFILES_HOME=""
	PACKAGE_MANAGER="dnf"

	CONFFILE="configs/${CONFFILE:-simple}"
}

__prep()
{
    local name="$1"
    cfg_section_${name}
    echo "[${name}]"
    if $enable; then
        true
    else
        info "Skip"
        false
    fi
}

set_global
source ./dotutil.d/utils
source ./dotutil.d/config-parser
source ./dotutil.d/run

verbose "Configuration file is: $CONFFILE"
cfg_parser $CONFFILE

# NOTE: the order in the list is important! for instance, if general goes after
#       extra, we do not know where DOTFILES_HOME is...
#       system should go after dotfiles. e.g.: ln .vim to ~ then install vim.
for section in general dotfiles system extra gnome git st; do
    if __prep $section; then
		HEADER=${SECTION_HEADER}
        __run_${section}
    fi
	echo
done
