---
- hosts: localhost
  remote_user: lvb

  tasks:
          # Misc
          - include: tasks/ansible.yml
          - include: tasks/packages.yml
          - include: tasks/fonts.yml
          - include: tasks/dotfiles.yml
