---
- hosts: localhost
  remote_user: lvb

  tasks:
          # Misc
          # - include: tasks/ansible.yml
          - include: tasks/packages.yml
          - include: tasks/fonts.yml
          - include: tasks/dotfiles.yml

          # Applications
          - include: tasks/vi.yml
          - include: tasks/git.yml
          - include: tasks/google-chrome.yml
          - include: tasks/gnome.yml
