- name: Download Dotfiles
  git:
          repo: 'https://github.com/liambeguin/dotfiles.git'
          dest: '{{ ansible_env.HOME }}/dev/dotfiles'

- name: Link Dotfiles
  file:
          src: '{{ ansible_env.HOME }}/dev/dotfiles/{{ item }}'
          dest: "{{ ansible_env.HOME }}/.{{ item }}"
          state: link
          force: yes
  with_items:
          - bashrc
          - vim
          - vimrc
          - Xresources
          - Xresources.d
          - tmux
          - tmux.conf
          - gitconfig
          - inputrc
          - tigrc
