- name: 'tmux: clone'
  git:
          repo: 'https://github.com/tmux/tmux.git'
          version: '3.0'
          dest: '{{ ansible_env.HOME }}/dev/tmux'

- name: 'tmux: install dependencies'
  become_user: root
  become: true
  package: name={{ item }}
  with_items:
          - automake
          - libevent
          - libevent-devel
          - ncurses
          - ncurses-devel
          - flex
          - bison

- name: 'tmux: autogen.sh'
  command: ./autogen.sh
  args:
          chdir: '{{ ansible_env.HOME }}/dev/tmux'

- name: 'tmux: configure'
  command: ./configure
  args:
          chdir: '{{ ansible_env.HOME }}/dev/tmux'

- name: 'tmux: compile'
  command: make
  args:
          chdir: '{{ ansible_env.HOME }}/dev/tmux'

- name: 'tmux: install'
  become_user: root
  become: true
  command: make install
  args:
          chdir: '{{ ansible_env.HOME }}/dev/tmux'
