#!/bin/sh
# this file contains all the different screen skins

# this can be
case $SCREEN_SKIN in
	"red")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{R}%S   %{= Kw} %=%{-} %-Lw%{= rW}%n%f %t%{-}%+Lw %=    %{R}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.r.}%?%3n %t%? [%h]%?'
	;;
	"green")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{G}%S   %{= Kw} %=%{-} %-Lw%{= gW}%n%f %t%{-}%+Lw %=    %{G}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.g.}%?%3n %t%? [%h]%?'
	;;
	"lightgreen")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{G}%S   %{= Kw} %=%{-} %-Lw%{= GW}%n%f %t%{-}%+Lw %=    %{G}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.G.}%?%3n %t%? [%h]%?'
	;;
	"yellow")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{Y}%S   %{= Kw} %=%{-} %-Lw%{= yW}%n%f %t%{-}%+Lw %=    %{Y}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.y.}%?%3n %t%? [%h]%?'
	;;
	"blue")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{B}%S   %{= Kw} %=%{-} %-Lw%{= bW}%n%f %t%{-}%+Lw %=    %{B}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.b.}%?%3n %t%? [%h]%?'
	;;
	"lightblue")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{B}%S   %{= Kw} %=%{-} %-Lw%{= BW}%n%f %t%{-}%+Lw %=    %{B}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.B.}%?%3n %t%? [%h]%?'
	;;
	"magenta")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{M}%S   %{= Kw} %=%{-} %-Lw%{= mW}%n%f %t%{-}%+Lw %=    %{M}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.m.}%?%3n %t%? [%h]%?'
	;;
	"cyan")
		export SCR_HARDSTAT='%{-}%{b KW} %H%{-b} %{C}%S   %{= Kw} %=%{-} %-Lw%{= cW}%n%f %t%{-}%+Lw %=    %{C}%D %M %d %{W}%C%a '
		export SCR_CAPTION='%?%F%{.c.}%?%3n %t%? [%h]%?'
	;;

	"old")
		export SCR_HARDSTAT='%{= kb}[%{kb}%H%? %1`%?%{b}][%{kb}%S%? %1`%?%{b}][%= %{= kw}%-w%{+b bw} %n*%?(%u)%? %{-}%+w %=%{b}][%{B}%D %M %d %{W}%C%A%{b}]'
		export SCR_CAPTION='%?%F%{.b.}%?%3n %t%? [%h]%?'
	;;
esac
