#!/usr/bin/env bash

# Install some packages we'll need to compile the driver below.
sudo dnf install gcc kernel-devel patch -y

# Create working dir for Broadcom driver files and patches.
WORKDIR="/tmp/hybrid_wl_f23.$$"
mkdir -p ${WORKDIR}

# Change to working dir.
cd ${WORKDIR}

if [ 'x86_64' == `uname -m` ]; then
	# 64-bit driver files.
	FILE='hybrid-v35_64-nodebug-pcoem-6_30_223_271.tar.gz'
else
	# 32-bit driver files.
	FILE='hybrid-v35-nodebug-pcoem-6_30_223_271.tar.gz'
fi

# Download Broadcom Linux Wi-Fi driver
wget http://www.broadcom.com/docs/linux_sta/$FILE

# Extract driver files.
tar zxvf $FILE

# Compile driver.
make clean && make

# Install driver.
sudo make install

# Update available drivers.
sudo depmod -a

# Load the driver.
sudo modprobe wl

# Load driver automatically at boot time.
echo 'wl' | sudo tee /etc/modules-load.d/wl.conf

# Connect to a Wi-Fi network via NetworkManager...
