#!/bin/sh
#
# This is used to disableSELinux
# ans start ssh daemon

echo "-- Disabling SELinux"
sudo sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
echo "-- You'll need to reboot for changes to take effect!"
sudo systemctl enable sshd.service
exit 0
